### ISSUE TITLE
Select app with arrows keys

### ISSUE THREAD

**Issue by glae** [kvakulo/Switcheroo#130]
Hi, it would be great if we could select an app with arrows keys (it is already doing when using Alt+Ctrl+Tab or Alt+Tab+S).

**Comment by andycjw** [comment]
this already works with arrow key, can you be more specific?
alt+j/k also works to move the selection in list up/down

**Comment by glae** [comment]
To be more specific : 
- alt+space ("Activate Switcheroo with this shortcut") then arrow keys works fine 
- alt+tab ("Activate Switcheroo with Alt+Tab") then arrow keys works fine 
-  alt+tab ("Activate Switcheroo with Alt+Tab") **and** "Automatically switch window when releasing alt+tab" then arrow keys **does not** work fine (I am using this 3rd setup)

**Comment by andycjw** [comment]
that's because it's supposed to work like the default windows 'alt+tab' with your 3rd setup, to move the selection, just keep tapping the 'tab', that's how the original 'alt-tab' works

**Comment by glae** [comment]
OK thanks for the explanation! I close the issue then.
