### ISSUE TITLE
Why Doesn't icons and app names show up properly

### ISSUE THREAD

**Issue by nicksspirit** [kvakulo/Switcheroo#139]
I have been using switcheroo which I installed through choclately and I noticed that when it comes to native windows applications, it doesn't show the icons and application names properly.

![image](https://user-images.githubusercontent.com/14257815/65813601-98beb800-e1a5-11e9-9b56-842dfe9717e4.png)
for the app name it would show 'ApplicationFrameHost'

Is this expected behavior?

**Comment by elig0n** [comment]
I'm afraid so. New Windows 'native' apps run in such way that causes this behavior. I might try to find a workaround later though. You may wish to follow my [fork's development](/elig0n/switcheroo) then

**Comment by nicksspirit** [comment]
Alright  thanks

**Comment by elig0n** [comment]
Please see this unmerged patch too: 
https://github.com/kvakulo/Switcheroo/pull/89/commits/2a1ef804aab786bd870b2e66c6b0fffccb95598a

**Comment by elig0n** [comment]
Please see this as well: https://github.com/kvakulo/Switcheroo/pull/89

**Comment by nicksspirit** [comment]
@elig0n It's not clear to me but is this pull request still a work in progress?

**Comment by elig0n** [comment]
@OdinTech3 I do not think so. It's a pull request which hasn't been merged. The author is unavailable for quite some time .
