### ISSUE TITLE
AWESOME TOOL, but will be better add support of switch different windows of same process

### ISSUE THREAD

**Issue by snowman** [kvakulo/Switcheroo#148]

**Comment by maessof91** [comment]
I would like this feature too, to press a hotkey and to cycle between windows of same process, currently i mainly use the app for switching between file explorer windows

**Comment by snowman** [comment]
Gist: [switch_windows_with_same_process_name.ahk](https://gist.github.com/snowman/a82bb832c4a2e0b3d89bbc9a1d2c7231)

**Comment by maessof91** [comment]
Thank you so much.

**Comment by snowman** [comment]
u r welcome
