### ISSUE TITLE
Add an option to customize the window close hotkey

### ISSUE THREAD

**Issue by HellBrick** [kvakulo/Switcheroo#22]
Personally I would find it more convenient (and intuitive) to use Del to close the selected window, just like Task Manager uses Del to kill the selected process. I guess whether or not Del is an appropriate default hotkey is a matter of personal taste, but it would definitely be nice for the user to be able to choose whatever hotkey he wants for closing the window.

**Comment by kvakulo** [comment]
Thanks for your feedback, @HellBrick! :+1:

I don't particularly like *CTRL+Enter* as the combination to close a window, and I agree *Del* would make more sense. (I didn't know that *Del* could be used in Task Manager - that's great knowledge!)

The problem with using *Del* in Switcheroo is that the textbox has focus while typing, so *Del* could suddenly mean two things; to delete a character or to close a window. Do you have an idea to work around that?

I would like to keep the solution to a non-configurable combination that works for everyone - just to keep it simple :)

/ Regin

**Comment by HellBrick** [comment]
I completely forgot Del can be used in the search field. On one hand, I have a theory that Del is barely used in Switcheroo or any search field in the world for that matter. Since the user is supposed to type a few characters and sees the filter applied as he types them, the cursor is normally located at the end of the text and fixing errors with Backspace is just much more convenient (and he can't delete anything with Del because there are no chars ahead of the cursor anyway). Using Del to delete text makes more sense for the different kinds of text editors, when you navigate through the text a lot and it's very possible to find yourself in a situation where you naturally want to delete something ahead of the cursor.

On the other hand, I see how choosing Del to be a hotkey for closing window can lead to some confusion. The users have a habit of it working the specific way in text fields, and it may be a bad idea to break that habit. The possible alternative that pops to mind is Ctrl+W that's used by a lot of software to close the current tab. It's not as intuitive as Del, but at least it's better than Ctrl+Enter (I think). Another idea is to reference Alt+F4 by using something like Ctrl+F4 or simply F4. And finally there's Shift+Del that's typically used for an alternative method to delete something (like deleting a file instead or moving it to Recycle bin). I guess the last choice is my personal favorite at the moment because it's the closest thing to Del and is fairly convenient to hit on a typical keyboard.

But as you can see, there's no clear answer what's best hotkey to use here, so I still think making it configurable is a good idea. There's another reason for it: having an option to change the hotkey will teach the users that this functionality actually exists. There's no way to figure it out on yourself by looking at the software if you haven't read the detailed description somewhere else.

**Comment by kvakulo** [comment]
I do agree that discoverability is a problem regarding the *Close window* feature. And I think it's the main problem.

I would still rather avoid adding it to the configuration, because I see it as a base feature that should just work the one way, and I don't see that many people would have an actually need to change this.

In another prototype of Switcheroo, I have added a context menu that shows the various shortcuts:
![image](https://cloud.githubusercontent.com/assets/359614/5822675/59b922b8-a0d6-11e4-95dc-ea4381f4aac9.png)

Maybe this in addition to an in-app *Help* window would help users to discover the feature?

Regarding the shortcut, I would agree to change it to `Ctrl+W`.

Is the a good enough solution from your viewpoint?

/Regin

**Comment by HellBrick** [comment]
However, you already allow changing the Alt + Space hotkey, which is definitely one of the cornerstones of the app. I really don't see why closing window doesn't deserve a config option. It definitely wouldn't be needed if it was possible to use something obvious like Del, but since this is not the case, I still believe making it configurable is the way to go here.

Context menu probably won't be of much use here, since Switcheroo is a very keyboard-oriented app, and most of its users probably won't even think of right-clicking a process. Help might help though (no pun intended): this way the hotkey will be mentioned somewhere in UI, in a place the user can actually get to.

And finally, I think that Ctrl+W is definitely better than Ctrl+Enter. It's not perfect, but it's good, and it doesn't look like there is a single perfect hotkey here.

**Comment by kvakulo** [comment]
I see a difference between `Alt+Space`and the `Close window` shortcut:

* The `Alt+Space` is a global hotkey and can easily conflict with other shortcuts or hotkeys from other programs, so it needs to be configurable.

* The `Close window` shortcut is local to Switcheroo, so there are no conflicts.

I think the added complexity (current and future) to be too high compared to the value the feature of making the shortcut customisable.

So for now the solution will be:
* From next release the `Close window` shortcut will change to `Ctrl+W`
* A *Help* window will be added to Switcheroo, so users can discover hidden functionality better
* If more people request customisable shortcuts within Switcheroo, I'll rethink my position on this :)

/Regin

**Comment by kvakulo** [comment]
I close this issue as `CTRL+W` is added as a shortcut. Help functionality is part of #24.

/Regin
