### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by pongo** [kvakulo/Switcheroo#26]
You should use TextOptions.TextFormattingMode="Display" 
http://wpf.2000things.com/2013/05/16/821-use-textformattingmode-to-make-text-look-more-clear/

**Comment by kvakulo** [comment]
Thanks for the hint, and sorry for my late response.

I'll experiment with the text formatting mode according to your suggestion.

/Regin

**Comment by kvakulo** [comment]
I've been playing around with this, and on my HDPI screen the default TextFormattingMode `Ideal` is actually more clear. I'll have to check up on this issue on a regular screen.

Do other people have issues with blurry text in Switcheroo? Please let me know if you do.

/Regin

**Comment by HellBrick** [comment]
I'm using Switcheroo on a typical 23" 1920x1080 screen and I don't see a problem with the way the text is rendered. However, I can't really say that the current option is better without actually comparing it to the alternatives =)

**Comment by kvakulo** [comment]
Here are two screenshots from my computer.

*Ideal*
![ideal](https://cloud.githubusercontent.com/assets/359614/6314721/1cbfef0e-b9ea-11e4-8b86-e692c685f27a.png)

*Display*
![display](https://cloud.githubusercontent.com/assets/359614/6314724/35d1bd92-b9ea-11e4-852d-800b30e1e065.png)

But I guess you really need to see the difference on your own screen. Here's a version of Switcheroo with TextFormattingMode set to `Display`: http://teamcity.codebetter.com/repository/download/Switcheroo/182243:id/switcheroo-portable.zip

**Comment by HellBrick** [comment]
I tried comparing the options side by side by adding this to `<Listbox.ItemContainerStyle>`:
```xaml
<Style.Triggers>
	<Trigger Property="ItemsControl.AlternationIndex" Value="0">
		<Setter Property="TextOptions.TextFormattingMode" Value="Display"></Setter>
	</Trigger>
	<Trigger Property="ItemsControl.AlternationIndex" Value="1">
		<Setter Property="TextOptions.TextFormattingMode" Value="Ideal"></Setter>
	</Trigger>
</Style.Triggers>
```

`Ideal` is indeed a bit more blurry. However, I actually prefer this blurry version over the `Display` - the later sometimes looks a bit uglier, and I don't see the readability suffering either way.

**Comment by kvakulo** [comment]
Nice way to try it out side-by-side, @HellBrick!

I won't make any changes to the font rendering for now, but I'll leave this ticket open for a while, just in case other people want to share their experiences.

/Regin

**Comment by kvakulo** [comment]
I'll close this issue for now, but it might be reopened if other users experience blurriness.

/Regin
