### ISSUE TITLE
Option sorted display, selection with . (dot)

### ISSUE THREAD

**Issue by rayhofmann** [kvakulo/Switcheroo#28]
A option to sort or group the list by applications would be nice.

Only if a group is matched it is expanded, to keep the list shorter and possibly all of it on the screen.

And selection with a dot would also be nice: chr.abc means select group of chr(ome) applications by application name and not by caption and then match to abc of the window caption.

**Comment by kvakulo** [comment]
Thanks for sharing your ideas! :+1: 

I especially like the one where you can search by application name, and then by window caption using eg the chr.abc syntax

The grouping by application seems a little less useful according to my personal usage, so I would like to understand that need a little better. Would you mind sharing a screenshot of a typical Switcheroo listing of your open windows, and how much screen space it takes up? Do you have specific programs that have many open windows?

/Regin

**Comment by rayhofmann** [comment]
You're welcome.



This is a typical screenshot.

I like to have the pdfs, vims, browsers etc. sorted/grouped first by 
application name and then by window title. Then application groups may 
be folded and only expanded when the application is selected with 
"app.", somewhat customizable to switch this off/on at least.

This way you will not have to scroll or guess what is hidden less with 
many windows, many open pdfs, etc..

Ray

Am 21.02.2015 um 19:39 schrieb Regin Lrsen:

**Comment by kvakulo** [comment]
Hi Ray,

The screenshot didn't make it through to GitHub. Would you mind uploading it directly on the issue, or alternatively sending it to me by e-mail (kvakulo at gmail)?

/Regin

**Comment by rayhofmann** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/11130957/6314239/b67931a4-ba09-11e4-9d5f-b726c2233f2f.png)

**Comment by kvakulo** [comment]
Thanks for the screenshot. Now I can certainly see why groupings per application or something similar would be quite useful.

/Regin

**Comment by rayhofmann** [comment]
And i want to express again how happy i am to find switcharoo, after trying some stpid alt-tab replacements and task switchers i felt lost with my desire to use much the keyboard.

Ray

----- Ursprüngliche Nachricht -----
Von: "Regin Larsen" <notifications@github.com>
Gesendet: ‎21.‎02.‎2015 21:42
An: "kvakulo/Switcheroo" <Switcheroo@noreply.github.com>
Cc: "rayhofmann" <rhofmann@rayed.de>
Betreff: Re: [Switcheroo] Option sorted display, selection with . (dot) (#28)

Thanks for the screenshot. Now I can certainly see why groupings per application or something similar would be quite useful.

/Regin

---

**Comment by kvakulo** [comment]
I'm glad to hear that you like Switcheroo. If you get other ideas of how to improve the program, please let me know.

/Regin

**Comment by kvakulo** [comment]
Hi @rayhofmann! I'm experimenting with the dot syntax order in #35. There's a build with that feature enabled if you want to try it out and see if this helps to navigate between your many open windows.

/ Regin

**Comment by rayhofmann** [comment]
Hi Regin,

i testet it a bit, it feels really good.

Sorting the list by application name and then by window title should 
also improve it, especially because the order now does not seem to have 
any consistency or meaning.
I could think of an alternative way to sort: By the start time of the 
application and then by window title, but still grouping same 
application names.

This means within groups there is sorted by window title, but the list 
of groups is sorted by the youngest/oldest application from the group.

You could have the most recently started listed first or vice versa this 
way.

Sorting is also useful for example when with time your open explorer 
windows accumulate and you have to clean up.

Also a quick selection of the first listed entries could be handy. Just 
use the same shift keys from the configured shortcut with numbers from 
1..9. Makes most sense with sorting.

Also switcheroo could be invoked in a second mode with a different 
shortcut like Alt+Tab, to replace and mimic the built in switcher 
completely. So to get to the previously started application you would 
press Alt+Tab.Tab, and Alt+Tab to get back to the most recent, the 
switcheroo display could be just the same just without the edit field 
for typing.

In this mode it is always sorted by application start time and then 
window title, no grouping, most recently started first.

And Alt+Shift-Tab for going backwards in the list could also be 
implemented then.

I like the "ctrl-w" feature, i was missing this until i found it. Very 
handy for cleaning up quickly.

The "." to get all windows of the focus app is also nice.

Scrolling seems not to work anymore when the list is longer than the screen.

Raymund Hofmann



Am 24.02.2015 um 03:57 schrieb Regin Larsen:

**Comment by kvakulo** [comment]
I greatly appreciate the feedback Raymund!

*Sorting*
Currently it works like this: Windows are initially sorted by the window order like in Windows' Alt+Tab feature. When you start to enter some text, then the windows are ordered by best match and then by the window order. It would be interesting to experiment with other sort orders as you propose.

*Quick selection*
It's a great idea to be able to quickly jump by a shortcut. I think that `Alt+1..9` would make the most sense since `Alt` is usually used to activate Switcheroo, so the finger is already in the position.

*Alt+Tab integration*
Actually Switcheroo can already be activated with `Alt+Tab` and `Shift+ Alt+Tab`. But only if the Alt+Tab integration is activated. This is done by right-clicking the Switcheroo icon in the notification area, clicking Options, and then checking "Activate Switcheroo with Alt+Tab". It seems like this option needs to be presented more clearly in the application, Github and the homepage so it's easier to discover.

*Scrolling*
I'll make sure to fix this issue and let you know.

/ Regin

**Comment by rayhofmann** [comment]
Am 24.02.2015 um 18:44 schrieb Regin Larsen:
>
> I greatly appreciate the feedback Raymund!
>
> /Sorting/
> Currently it works like this: Windows are initially sorted by the 
> window order like in Windows' Alt+Tab feature. When you start to enter 
> some text, then the windows are ordered by best match and then by the 
> window order. It would be interesting to experiment with other sort 
> orders as you propose.
>
> /Quick selection/
> It's a great idea to be able to quickly jump by a shortcut. I think 
> that |Alt+1..9| would make the most sense since |Alt| is usually used 
> to activate Switcheroo, so the finger is already in the position.
>
> /Alt+Tab integration/
> Actually Switcheroo can already be activated with |Alt+Tab| and 
> |Shift+ Alt+Tab|. But only if the Alt+Tab integration is activated. 
> This is done by right-clicking the Switcheroo icon in the notification 
> area, clicking Options, and then checking "Activate Switcheroo with 
> Alt+Tab". It seems like this option needs to be presented more clearly 
> in the application, Github and the homepage so it's easier to discover.
>
Ah, i overlooked that.

But still i proposed to change the switcheroo behaviour then so as soon 
as you release the ALT the selected window is activated, just like 
Windows Alt+Tab. This is where the different sorting styles, user 
configurable to some extent, make Switcheroo the better ALT+Tab replacement.

Raymund

**Comment by kvakulo** [comment]
It's now possible to switch to another window when Alt+Tab is released.

I close this issue, but please let me know if you should still experience problems with other functionalities :)
