### ISSUE TITLE
Filter by process name using dot syntax

### ISSUE THREAD

**Issue by kvakulo** [kvakulo/Switcheroo#35]
As proposed by @rayhofmann in #28 it should be possible to search by process name.

He proposed this syntax `chr.abc` where `chr` refers to the process name and `abc` refers to the window caption.

I have tried to implement this in the following commit as an experiment to try out how it feels.

As an extra feature: If a process name is left out, and one just searches for `.abc` then the process name filter is implicitly set to the process name of the foreground window. This seems nice when switching between different windows of the application that you currently have in the foreground. (Just activate Switcheroo, type `.` and choose any other window from the same application)

**Comment by kvakulo** [comment]
Here's build with this feature if anybody wants to try it out:
http://teamcity.codebetter.com/repository/download/Switcheroo/182800:id/switcheroo-portable.zip

Please let me know what you think! :)

**Comment by kvakulo** [comment]
This feature is going into the next release

**Comment by rayhofmann** [comment]
Looking forward, still using your prototype.

Ray

-----Original Message-----

**Comment by rayhofmann** [comment]
Hey!

 

Important message, please visit <http://chipauto24.ru/opposite.php?7>

 

rhofmann@rayed.de

**Comment by rayhofmann** [comment]
Hello!

 

New message, please read <http://softcraftltd.co.uk/number.php?yj2ig>

 

rhofmann@rayed.de

**Comment by rayhofmann** [comment]
Hey!

 

Open message <http://colunna.com.br/service.php?h>

 

rhofmann@rayed.de

**Comment by rayhofmann** [comment]
Hello,


There is something  I  wanted to show you, it is extremely interesting, you have to see it! Take a look here  <http://develop.spikedpunch.com/aejnze>

rhofmann@rayed.de

**Comment by rayhofmann** [comment]
Dear! 
We've got some great  news for you! Just take  a look  <http://mofawaltu.fabstaff.com/aeqckbfh>


Warm regards, Raymund Hofmann
