### ISSUE TITLE
Switcheroo suggests to update to the public version when built from master

### ISSUE THREAD

**Issue by HellBrick** [kvakulo/Switcheroo#40]
It seems Switcheroo's version in master is set to a value that's lower than the current public version for some reason, which triggers update prompt when running custom builds.

**Comment by kvakulo** [comment]
Thanks for the PR!

The version numbers are set when building Switcheroo in TeamCity, so I'm afraid that the version number in master will keep being behind and forgotten to be updated accordingly.

So I've solved it a bit differently in that version checking is now disabled altogether if building and running Switcheroo locally.

/Regin
