### ISSUE TITLE
Can't close Task Manager

### ISSUE THREAD

**Issue by HellBrick** [kvakulo/Switcheroo#42]
Switcheroo constantly fails to close Task Manager when running on Windows 8 (haven't tried with other  Windows versions). I understand there are windows that intercept closing and prevent it (typically to display some kind of 'save changes?' dialog), but such windows do this regardless of the way they are closed: Alt+F4, right-click on the taskbar icon -> Close window or Switcheroo's Ctrl+W all behave the same. Task Manager, however, can be closed by Alt+F4 and the taskbar icon, but can't be closed by Switcheroo, so it seems like a bug.

**Comment by kvakulo** [comment]
It would be nice to get this solved, so the close feature works more consistently. It also affects chat windows in Trillian.

I guess that these windows ignore the `WM_CLOSE` message. Further research is needed to figure out what can be done instead.

/Regin

**Comment by kvakulo** [comment]
`WM_SYSCOMMAND + SC_CLOSE` works for Task Manager and Trillian.

I'll try this out for a while and see if there are any problems making just this change, or if there are scenarios where this solution isn't working.

/Regin
