### ISSUE TITLE
SmartGit window is missing from the window list if a child window is opened

### ISSUE THREAD

**Issue by HellBrick** [kvakulo/Switcheroo#43]
I think I saw SmartGit window on one of your screenshots, which is good, because this means you can easily reproduce the bug ;)

1. Open SmartGit
2. Open Switcheroo to verify SmartGit window is correctly displayed in the list by default
3. Switch to SmartGit, hit `Ctrl+R` to display reset window
4. Open Switcheroo, BOOM! - there's no SmartGit window in the list anymore

**Comment by kvakulo** [comment]
5. Reproduced. Thanks for reporting!

The mistake also seems to be with the Commit window, and probably other pop-up windows too. Seems like a 0.9.1 release is forthcoming ASAP :crystal_ball:

**Comment by HellBrick** [comment]
I'm not sure if it's relevant or a separate issue, but Guitar pro 5 doesn't appear in the list whatsoever, even if though it doesn't display any pop-ups. I'll test it again when the current issue is fixed to check if this is the same problem.

**Comment by kvakulo** [comment]
@HellBrick Do you have a chance to check if this change fixes the issue? Also if Guitar pro 5 appears now, or if it is another issue.

**Comment by HellBrick** [comment]
Finally got the chance to check it: your commit successfully fixes both issues. Thanks!

**Comment by kvakulo** [comment]
Perfect! I'll prepare to push out a new release with this fix included :)
