### ISSUE TITLE
[feature request] Make Alt key work as Return

### ISSUE THREAD

**Issue by amynbe** [kvakulo/Switcheroo#47]
I would like to use switcheroo with alt-tab with one hand: alt-tab to pop-pup switcheroo, then alt to switch to the selected window. Being forced to press return to select a window forces me to use two hands.
Seems so far tab key is not used in switcheroo, so it would'nt do any harm.

**Comment by kvakulo** [comment]
Thanks for your feature request @amynbe!

It's an interesting idea and I will try it out. I'm a bit worried about using `Alt` for this since it's already used for `Alt+Tab` and `Alt+Space`, but maybe it's not a problem even though :)

If you got any other ideas for Switcheroo, then feel free to let me know!

/ Regin

**Comment by egabrum** [comment]
I came to request something very similar. I find annoying having to always operate Switcheroo with 2 hands.

I was thinking that Switcheroo could work similarly to the original task switcher in Windows:
1) The user hits Alt+Tab and keeps Alt pressed.
At this point, the user has 2 options:
2a) Release the Alt key and use the other great features of Switcheroo (use arrows, type for filtering, press Ctrl+Enter to close a window, ...)
2b) Hit Tab again multiple times until selecting the desired task and release Alt to switch to that task.

As it is now, the second Alt+Tab closes the Switcheroo window, but we could dedicate Esc instead for that.
I really would love to have this '2b' option.

P.S. Also, is this project still alive?

**Comment by guilhas** [comment]
Hello,

I was also looking for something like this.

Maybe 2 shortcuts:
- One with Alt-Tab behaviour, on Alt release, close.
- And Alt-Space with current behaviour, plus press Alt instead of enter.

**Comment by kvakulo** [comment]
Hi @egabrum and @guilhas,

Visual Studio Code has a feature for switching between files (CTRL+E). If you press CTRL+E once, then it will select the active file and allow filtering or commands, but if you press CTRL+E more than once, then it will switch to that file, when CTRL is released.

I'm thinking it could be the same in Switcheroo: If you click Alt+Tab once, then the current window is selected, and it's possible to search by text and use the allows. But if you click on Alt+Tab more than once, then it will change to the selected window when Alt is released.

How does that sound?

**Comment by kvakulo** [comment]
Alright, I have tried to implement this:

1. The active window is now listed at the top of the list
2. If you press Alt+Tab more than once, then Switcheroo switches to the selected window
3. If you press Alt, then Switcheroo switches to the selected window

Would you try it out, and see if it works well for your use cases?

[switcheroo-portable.zip](https://github.com/kvakulo/Switcheroo/files/581570/switcheroo-portable.zip)

**Comment by amynbe** [comment]
Dear @kvakulo , that's very nice, you implemented both requirements. It's working very well.

**Comment by egabrum** [comment]
Regin,

That's is nice, but it does not work consistently if you use a different
shortcut.

In my case, I use Alt+Q for switcheroo, and does not behave as you
described.

The reason why I don't use Alt+Tab for switcheroo is because it can be
pretty slow loading at times (and requires 2 keystrokes to just switch back
and forth between 2 tasks), and I like to use the OS Alt+Tab feature to
switch task back and forth quickly and with only one key stroke

Thanks

**Comment by kvakulo** [comment]
Thanks for your feedback, @amynbe and @egabrum!

I have fixed an issue with the Alt-key logic when activating Switcheroo through an hotkey including Alt. Would you mind trying it out, and report back if it fixes the issue @egabrum? :)

https://ci.appveyor.com/api/buildjobs/787wjqdd90s02htl/artifacts/Installer%2FOutput%2Fswitcheroo-portable.zip

**Comment by egabrum** [comment]
@kvakulo , my shortcut is Alt-q
With Alt-Tab:
1) Alt-Tab open Switcheroo
2) Alt-Tab (or releasing Alt and hitting only Tab) changes the selection in the drop-down list of tasks.
3) Releasing Tab (or pushing Alt or Enter if used only Tab above) switches to the tasks currently highlighted in the list.

Wit my shortcut (Alt-q):
1) Alt-q open Switcheroo
2) Alt-q again closes the Switcheroo window. Hitting only 'q' enters 'q'in the text box.
3) N/A

**Comment by kvakulo** [comment]
ℹ️ In v0.10.0-beta.1 `Alt` can be used as `Enter`
