### ISSUE TITLE
AHK (autohotkey) Message box not in window list

### ISSUE THREAD

**Issue by jaredbidlow** [kvakulo/Switcheroo#53]

**Comment by kvakulo** [comment]
Thanks for the report! I can conform that the message boxes are missing in Switcheroo.

With an ahk script like this...
```
MsgBox, 4,, Would you like to continue? (press Yes or No)
IfMsgBox Yes
    MsgBox You pressed Yes.
else
    MsgBox You pressed No.
```

...the message boxes are included in the native alt+tab, but not in Switcheroo's list.

/Regin
