### ISSUE TITLE
Crashes on Restart

### ISSUE THREAD

**Issue by ImagineInfinity** [kvakulo/Switcheroo#61]
When I install switcheroo and open wox to try to type something, it crashes.
If I open wox and go to plugin settings without trying to type anything, and click on "Switcheroo for wox", it comes up with this error:
`Could not load type 'Wox.Infrastructure.Storage.BaseStorage'1' from assembly 'Wox.Infrastructure, Version=1.2.882.0, Culture=neutral, PublicKeyToken=null'.`

**Comment by bradrhodes** [comment]
This repo is for Switcheroo the standalone application.

I could be wrong but I think you want to post this issue here: https://github.com/Wox-launcher/Wox.Plugin.Switcheroo.  Which is the repo for the Wox Switcheroo plugin.

**Comment by MiND951** [comment]
Yeah, it was. Sorry!
