### ISSUE TITLE
Add ability to multiselect entries

### ISSUE THREAD

**Issue by holymoo** [kvakulo/Switcheroo#63]
I find myself often wanting to bring multiple windows to the foreground at the same time. It would be nice if I could select multiple entries via shift+ down and bring them into the foreground.

**Comment by kvakulo** [comment]
Thanks for your suggestion, @holymoo (and sorry for answering so late!)

If other people are interested in this feature, please let me know.

And if anybody would like to implement it, I'd be more than happy to accept your pull request 😸
