### ISSUE TITLE
extend to launching applications

### ISSUE THREAD

**Issue by alapolloni** [kvakulo/Switcheroo#66]
(switching from macOS), it'd be nice to launch an application if it isn't already running....

**Comment by kvakulo** [comment]
Thanks for your idea, @alapolloni!

I don't have plans for extending Switcheroo with that functionality for the time being. But I would gladly accept a pull request if you or somebody else reading this feels like adding the feature :)

**Comment by vjdw** [comment]
I'm looking at how this could work. I think perhaps include applications that aren't running into the list only when:

1. Query text has been entered.
2. When there is an exact match for that app (or the match score is over a certain value?)

In the results list, applications that aren't running should also be highlighted somehow.

**Comment by kvakulo** [comment]
I'm closing this issue for now as it's not the main focus of the application. However I'm still willing to accept PR's if someone comes up with a good way of integrating it into Switcheroo.
