### ISSUE TITLE
One mouse click

### ISSUE THREAD

**Issue by guilhas** [kvakulo/Switcheroo#67]
Hello,

Would it be possible, on click, in one item in the window list, to change to it? Currently is double click.

Regards,
Lino

**Comment by kvakulo** [comment]
This would interfere with multiselect from #71. Please let me know if you have an idea how to combine the two features.

**Comment by guilhas** [comment]
Not sure if it is a bug but I am not able to multi select. Looks good anyway Mouse click + release Alt.

**Comment by elig0n** [comment]
Use shift & control along with mouse left click to select
