### ISSUE TITLE
[New] Simple Alt - Tab replacement

### ISSUE THREAD

**Issue by guilhas** [kvakulo/Switcheroo#72]
Hello,

I like Switcheroo better than windows default. (icon + window title list)
Is there possible to have a setting to make Switcheroo Alt - Tab shortcut behave like windows one?
Example: On first Alt release change to previous application.

Regards,
Lino

**Comment by Leon99** [comment]
Fully support this one. In addition, current Switcheroo behaviour maps to Ctrl+Alt+Tab, so it would be nice to support overriding that hotkey as well.

**Comment by kvakulo** [comment]
Please try out v0.10.0-beta.1 😄 

Now you can Auto Switch with `Alt+Tab` and also `Ctrl+Alt+Tab` 🎉
