### ISSUE TITLE
Alt + Tab override and no other hotkey

### ISSUE THREAD

**Issue by SzymonKatra** [kvakulo/Switcheroo#76]
I've noticed one problem using Alt + Tab override. When I don't have any other hotkey it causes problems with "Backspace". When Switcheroo is open, it simply disappears, and when it's not visible then typing backspace causes to open Switcheroo.

Windows 10 Home x64

**Steps to reproduce:**
1. Start Switcheroo
2. Right click on Switcheroo on notification area and select "Options"
3. Remove hotkey: "Activate Switcheroo with this shortcut".
4. Check off "Activate Switcheroo with Alt + Tab".
5. Press OK
6. Now try to press backspace. Switcheroo will appear. Also, open Switcheroo with alt+tab, type something, and try to delete it using backspace. Switcheroo will disappear.

**Comment by tarikguney** [comment]
I think the solution should be that when ALT + TAB is checked, the other field should be disabled and the content must be ignored. I am using this a lot so I will contribute that enhancement.

**Comment by tarikguney** [comment]
@SzymonKatra https://github.com/kvakulo/Switcheroo/pull/77

This PR will fix your problem.

**Comment by tarikguney** [comment]
@kvakulo I think we can close this issue.
